name: Build
on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build-${{ matrix.build-type }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [nightly, nightlz]

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 22
      uses: actions/setup-java@main
      with:
        java-version: 22
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main

    - name: Modify strings.xml for nightlz
      if: matrix.build-type == 'nightlz'
      run: |
        cd app/src/main/res/values
        sed -i 's|<string name="app_name" translatable="false">"Aurora Store"</string>|<string name="app_name" translatable="false">"Aurora Store Nightlz"</string>|' strings.xml

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build vanilla nightly
      run: |
        ./gradlew assembleVanillaNightly

    # - name: Build huawei
    #   run: |
    #     ./gradlew assembleHuaweiRelease

    - name: Upload Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: AuroraStore-${{ matrix.build-type }}
        path: app/build/outputs/*
